//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BencineraDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estanque
    {
        public string CodigoEstanque { get; set; }
        public string TipoCombustible { get; set; }
        public Nullable<double> CantidadTotal { get; set; }
        public Nullable<double> CantidadUtilizada { get; set; }
        public Nullable<int> Id_Sucursal { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
    }
}
