//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BencineraDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Rut { get; set; }
        public string Turno { get; set; }
        public string Tipo_Usuario { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
